on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      
      - uses: actions/checkout@v3
      - name: "login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{secrets.DOCKER_TOKEN}}
      - name: "building image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/image2
      - name: "push image"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/image2

      
  
